namespace Mongin.Mechanics
{
    public static class TypeTable
    {
        public readonly static Dictionary<Typing, Dictionary<Typing, TypeEffectiveness>> Value = new()
        {
            {
                Typing.Normal,
                new()
                {
                    {
                        Typing.Normal,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fire,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Water,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Electric,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Grass,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ice,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fighting,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Poison,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ground,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Flying,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Psychic,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Bug,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Rock,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Ghost,
                        TypeEffectiveness.NoEffect
                    },
                    {
                        Typing.Dragon,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Dark,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Steel,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Fairy,
                        TypeEffectiveness.Normal
                    },
                }
            },

            {
                Typing.Fire,
                new()
                {
                    {
                        Typing.Normal,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fire,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Water,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Electric,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Grass,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Ice,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Fighting,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Poison,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ground,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Flying,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Psychic,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Bug,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Rock,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Ghost,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Dragon,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Dark,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Steel,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Fairy,
                        TypeEffectiveness.Normal
                    },
                }
            },

            {
                Typing.Water,
                new()
                {
                    {
                        Typing.Normal,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fire,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Water,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Electric,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Grass,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Ice,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fighting,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Poison,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ground,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Flying,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Psychic,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Bug,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Rock,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Ghost,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Dragon,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Dark,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Steel,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fairy,
                        TypeEffectiveness.Normal
                    },
                }
            },

            {
                Typing.Electric,
                new()
                {
                    {
                        Typing.Normal,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fire,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Water,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Electric,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Grass,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Ice,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fighting,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Poison,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ground,
                        TypeEffectiveness.NoEffect
                    },
                    {
                        Typing.Flying,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Psychic,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Bug,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Rock,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ghost,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Dragon,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Dark,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Steel,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fairy,
                        TypeEffectiveness.Normal
                    },
                }
            },

            {
                Typing.Grass,
                new()
                {
                    {
                        Typing.Normal,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fire,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Water,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Electric,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Grass,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Ice,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fighting,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Poison,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Ground,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Flying,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Psychic,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Bug,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Rock,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Ghost,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Dragon,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Dark,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Steel,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Fairy,
                        TypeEffectiveness.Normal
                    },
                }
            },

            {
                Typing.Ice,
                new()
                {
                    {
                        Typing.Normal,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fire,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Water,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Electric,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Grass,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Ice,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Fighting,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Poison,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ground,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Flying,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Psychic,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Bug,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Rock,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ghost,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Dragon,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Dark,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Steel,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Fairy,
                        TypeEffectiveness.Normal
                    },
                }
            },

            {
                Typing.Fighting,
                new()
                {
                    {
                        Typing.Normal,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Fire,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Water,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Electric,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Grass,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ice,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Fighting,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Poison,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Ground,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Flying,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Psychic,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Bug,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Rock,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Ghost,
                        TypeEffectiveness.NoEffect
                    },
                    {
                        Typing.Dragon,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Dark,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Steel,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Fairy,
                        TypeEffectiveness.NotVeryEffective
                    },
                }
            },

            {
                Typing.Poison,
                new()
                {
                    {
                        Typing.Normal,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fire,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Water,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Electric,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Grass,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Ice,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fighting,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Poison,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Ground,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Flying,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Psychic,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Bug,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Rock,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Ghost,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Dragon,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Dark,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Steel,
                        TypeEffectiveness.NoEffect
                    },
                    {
                        Typing.Fairy,
                        TypeEffectiveness.SuperEffective
                    },
                }
            },

            {
                Typing.Ground,
                new()
                {
                    {
                        Typing.Normal,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fire,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Water,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Electric,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Grass,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Ice,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fighting,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Poison,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Ground,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Flying,
                        TypeEffectiveness.NoEffect
                    },
                    {
                        Typing.Psychic,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Bug,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Rock,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Ghost,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Dragon,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Dark,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Steel,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Fairy,
                        TypeEffectiveness.Normal
                    },
                }
            },

            {
                Typing.Flying,
                new()
                {
                    {
                        Typing.Normal,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fire,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Water,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Electric,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Grass,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Ice,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fighting,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Poison,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ground,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Flying,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Psychic,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Bug,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Rock,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Ghost,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Dragon,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Dark,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Steel,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Fairy,
                        TypeEffectiveness.Normal
                    },
                }
            },

            {
                Typing.Psychic,
                new()
                {
                    {
                        Typing.Normal,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fire,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Water,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Electric,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Grass,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ice,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fighting,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Poison,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Ground,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Flying,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Psychic,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Bug,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Rock,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ghost,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Dragon,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Dark,
                        TypeEffectiveness.NoEffect
                    },
                    {
                        Typing.Steel,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Fairy,
                        TypeEffectiveness.Normal
                    },
                }
            },

            {
                Typing.Bug,
                new()
                {
                    {
                        Typing.Normal,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fire,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Water,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Electric,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Grass,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Ice,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fighting,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Poison,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Ground,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Flying,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Psychic,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Bug,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Rock,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ghost,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Dragon,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Dark,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Steel,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Fairy,
                        TypeEffectiveness.NotVeryEffective
                    },
                }
            },

            {
                Typing.Rock,
                new()
                {
                    {
                        Typing.Normal,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fire,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Water,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Electric,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Grass,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ice,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Fighting,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Poison,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ground,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Flying,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Psychic,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Bug,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Rock,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ghost,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Dragon,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Dark,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Steel,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Fairy,
                        TypeEffectiveness.Normal
                    },
                }
            },

            {
                Typing.Ghost,
                new()
                {
                    {
                        Typing.Normal,
                        TypeEffectiveness.NoEffect
                    },
                    {
                        Typing.Fire,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Water,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Electric,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Grass,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ice,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fighting,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Poison,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ground,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Flying,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Psychic,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Bug,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Rock,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ghost,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Dragon,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Dark,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Steel,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fairy,
                        TypeEffectiveness.Normal
                    },
                }
            },

            {
                Typing.Dragon,
                new()
                {
                    {
                        Typing.Normal,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fire,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Water,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Electric,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Grass,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ice,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fighting,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Poison,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ground,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Flying,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Psychic,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Bug,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Rock,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ghost,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Dragon,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Dark,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Steel,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Fairy,
                        TypeEffectiveness.Normal
                    },
                }
            },

            {
                Typing.Dark,
                new()
                {
                    {
                        Typing.Normal,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fire,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Water,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Electric,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Grass,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ice,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fighting,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Poison,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ground,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Flying,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Psychic,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Bug,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Rock,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ghost,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Dragon,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Dark,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Steel,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fairy,
                        TypeEffectiveness.NotVeryEffective
                    },
                }
            },

            {
                Typing.Steel,
                new()
                {
                    {
                        Typing.Normal,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fire,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Water,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Electric,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Grass,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ice,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Fighting,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Poison,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ground,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Flying,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Psychic,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Bug,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Rock,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Ghost,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Dragon,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Dark,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Steel,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Fairy,
                        TypeEffectiveness.SuperEffective
                    },
                }
            },

            {
                Typing.Fairy,
                new()
                {
                    {
                        Typing.Normal,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fire,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Water,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Electric,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Grass,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ice,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Fighting,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Poison,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Ground,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Flying,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Psychic,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Bug,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Rock,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Ghost,
                        TypeEffectiveness.Normal
                    },
                    {
                        Typing.Dragon,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Dark,
                        TypeEffectiveness.SuperEffective
                    },
                    {
                        Typing.Steel,
                        TypeEffectiveness.NotVeryEffective
                    },
                    {
                        Typing.Fairy,
                        TypeEffectiveness.Normal
                    },
                }
            },
        };
    }
}